server:
  port: 8080
  servlet:
    context-path: /hc
  #address: 192.168.1.19
spring:
  profiles:
    active: dev,jdbc
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
